nodeLinker: node-modules

packageExtensions:
  "@nrwl/devkit@19.6.5":
    peerDependencies:
      nx: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
