version: "3.4"
services:
  backend:
    extends:
      file: docker-compose.yml
      service: backend

  influxdb:
    image: influxdb:1.8
    networks:
      - k6
      - grafana
      - influxdb
    ports:
      - "8086"
    environment:
      - DOCKER_INFLUXDB_INIT_ORG=k6
      - DOCKER_INFLUXDB_INIT_BUCKET=k6
      - DOCKER_INFLUXDB_INIT_USERNAME=k6
      - DOCKER_INFLUXDB_INIT_PASSWORD=k6
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=EEKpryGZk8pVDXmIuy484BKUxM5jOEDv7YNoeNZUbsNbpbPbP6kK_qY9Zsyw7zNnlZ7pHG16FYzNaqwLMBUz8g==
    volumes:
      - ./load-testing/setup/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf

  grafana:
    image: grafana/grafana:9.3.8
    networks:
      - grafana
      - influxdb
    ports:
      - "2000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./load-testing/setup/grafana:/etc/grafana/provisioning/

  k6:
    image: grafana/k6:latest
    entrypoint: ["tail", "-f", "/dev/null"]
    working_dir: "/"
    ports:
      - "6565"
    links:
      - influxdb
      - backend
    networks:
      - k6
      - influxdb
      - backend
    environment:
      - K6_OUT=influxdb=http://influxdb:8086
      - K6_INFLUXDB_ORGANIZATION=k6
      - K6_INFLUXDB_BUCKET=k6
      - K6_INFLUXDB_TOKEN=EEKpryGZk8pVDXmIuy484BKUxM5jOEDv7YNoeNZUbsNbpbPbP6kK_qY9Zsyw7zNnlZ7pHG16FYzNaqwLMBUz8g==
      - BASE_URL=http://backend/v1
    volumes:
      - ./backend/test:/test/backend/test

networks:
  k6:
  grafana:
  influxdb:
  backend:
