version: "3.4"
services:
  frontend:
    image: docker-registry.twinsoft.es/cocobay-app-frontend:staging
    container_name: cocobay-app-frontend
    restart: unless-stopped
    ports:
      - "3001:80"

  backend:
    image: docker-registry.twinsoft.es/cocobay-app-backend:staging
    container_name: cocobay-app-backend
    restart: unless-stopped
    networks:
      - backend
    links:
      - mongodb
    environment:
      PORT: "80"
      MONGODB_URI: "mongodb://root:root@mongodb:27017/"
    env_file:
      - .env.backend
    ports:
      - "3002:80"

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017"

networks:
  backend:
