version: "3.4"
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base

  frontend:
    build:
      context: .
      target: frontend
      dockerfile: Dockerfile.frontend
    container_name: cocobay-app-frontend
    depends_on:
      - base
    ports:
      - "3000:80"

  backend:
    build:
      context: .
      target: backend
      dockerfile: Dockerfile.backend
    container_name: cocobay-app-backend
    depends_on:
      - base
    networks:
      - backend
    links:
      - mongodb
    environment:
      PORT: "80"
      MONGODB_URI: "mongodb://mongodb:27017/cocobay"
    ports:
      - "3001:80"

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"

networks:
  backend:
