version: "3.4"
services:
  frontend:
    image: docker-registry.twinsoft.es/cocobay-app-frontend:staging
    container_name: cocobay-app-frontend
    restart: unless-stopped
    ports:
      - "3001:80"
