# syntax=docker/dockerfile:1.9.0-labs
FROM base AS frontend-build

COPY . /app
RUN mv packages/frontend/config/local.template.ts packages/frontend/config/local.ts

ARG ENV
ARG APP_VERSION=edge
RUN NEXT_PUBLIC_ENVIRONMENT=${ENV} \
    NEXT_PUBLIC_APP_VERSION=${APP_VERSION} \
    NEXT_PUBLIC_APP_BUILD_TIME=$(date +"%Y-%m-%dT%H:%M:%S%z") \
    yarn workspace frontend build

FROM nginx:alpine AS frontend

COPY --from=frontend-build /app/packages/frontend/out /usr/share/nginx/html