version: "3.4"
services:
  frontend:
    build:
      context: .
      target: frontend
      dockerfile: Dockerfile.frontend
    container_name: cocobay-app-frontend
    ports:
      - "3000:80"

  backend:
    build:
      context: .
      target: backend
      dockerfile: Dockerfile.backend
    container_name: cocobay-app-backend
    networks:
      - backend
    environment:
      PORT: "80"
    ports:
      - "3001:80"

networks:
  backend:
