version: "3.4"
services:
  frontend:
    build:
      context: .
      target: frontend
      dockerfile: Dockerfile.frontend
    container_name: cocobay-app-frontend
    ports:
      - "3000:80"

  backend:
    build:
      context: .
      target: backend
      dockerfile: Dockerfile.backend
    container_name: cocobay-app-backend
    networks:
      - backend
    links:
      - mongodb
    environment:
      PORT: "80"
      MONGODB_URI: "mongodb://root:example@mongodb:27017/"
    ports:
      - "3001:80"

  mongodb:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

networks:
  backend:
