# syntax=docker/dockerfile:1.9.0-labs
FROM node:22 AS frontend-build

RUN mkdir /app
WORKDIR /app

#Tell yarn we're building in CI
ENV CI=true

COPY --parents package.json yarn.lock .yarnrc.yml .yarn/ packages/*/package.json packages/*/yarn.lock ./

RUN yarn workspace frontend install --immutable

COPY . /app

RUN NEXT_PUBLIC_ENVIRONMENT=prod yarn workspace frontend build

FROM nginx:alpine AS frontend

COPY --from=frontend-build /app/packages/frontend/out /usr/share/nginx/html