name: Build backend

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-build-exists:
    name: Checking if build exists
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.check-build-exists.outputs.exists }}
    steps:
      - name: Set version number
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: cocobay-app-backend
          tags: |
            type=sha,prefix=,format=long

      - name: Check if already built
        id: "check-build-exists"
        run: |
          echo "Checking if version ${{ steps.meta.outputs.version }} exists"
          (curl -u "${{ secrets.DOCKER_REGISTRY_USERNAME }}:${{ secrets.DOCKER_REGISTRY_PASSWORD }}" \
            "https://${{ vars.DOCKER_REGISTRY }}/v2/cocobay-app-backend/tags/list" | \
            grep -q "\"${{ steps.meta.outputs.version }}\"" && \
            echo "Build ${{ steps.meta.outputs.version }} already exists in registry, no need to rebuild" && \
            echo "::set-output name=exists::true"
          ) || \
          echo "Build ${{ steps.meta.outputs.version }} does not exist yet"

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: check-build-exists
    if: ${{ needs.check-build-exists.outputs.exists != 'true' }}
    outputs:
      tags: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set version number
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: cocobay-app-backend
          tags: |
            type=sha,prefix=,format=long

      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build docker image
        run: |
          docker build . --file Dockerfile.backend --target backend \
            -t ${{ vars.DOCKER_REGISTRY }}/${{ steps.meta.outputs.tags }} --pull=true

  smoke-test:
    name: Smoke test
    runs-on: ubuntu-latest
    needs:
      - check-build-exists
      - build
    if: ${{ needs.check-build-exists.outputs.exists != 'true' }}
    steps:
      - name: Smoke test
        id: run_docker_smoke_test
        run: |
          docker run -d --env PORT=80 -p 80 --name cocobay-app-backend \
            ${{ vars.DOCKER_REGISTRY }}/${{ needs.build.outputs.tags }}
          docker run --network container:cocobay-app-backend appropriate/curl --retry 5 --retry-connrefused http://localhost

      - name: Tear down smoke test
        if: always()
        run: |
          docker stop cocobay-app-backend
          docker rm cocobay-app-backend

      - name: Push image to repository
        run: |
          docker push ${{ vars.DOCKER_REGISTRY }}/${{ needs.build.outputs.tags }}
