name: Build

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      version:
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-build:
    name: Backend
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      docker-build-args: ". --file Dockerfile.backend --target backend \
        --build-arg ENV=${{ inputs.env }} --build-arg APP_VERSION=${{ inputs.version }}"
      base-app-name: cocobay-app-base
      app-name: cocobay-app-backend
      version: ${{ inputs.version }}

  frontend-build:
    name: Frontend
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      docker-build-args: ". --file Dockerfile.frontend --target frontend \
        --build-arg ENV=${{ inputs.env }} --build-arg APP_VERSION=${{ inputs.version }}"
      base-app-name: cocobay-app-base
      app-name: cocobay-app-frontend
      version: ${{ inputs.version }}
