name: Build frontend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build"
        required: true
        default: "main"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set version number
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: cocobay-app-frontend
          tags: |
            type=raw,value={{date 'YYYYMMDDHHmmSS'}}
      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Build docker image
        run: |
          docker build . --file Dockerfile --target frontend \
            -t ${{ vars.DOCKER_REGISTRY }}/${{ steps.meta.outputs.tags }} --pull=true
      - name: Smoke test
        id: run_docker_smoke_test
        run: |
          docker run -d -p 3000:80 --name cocobay-app-frontend \
            ${{ vars.DOCKER_REGISTRY }}/${{ steps.meta.outputs.tags }}
          curl --retry 3 --retry-delay 5 --fail http://localhost:3000/
          docker stop cocobay-app-frontend
          docker rm cocobay-app-frontend
      - name: Tag build for release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker tag ${{ vars.DOCKER_REGISTRY }}/${{ steps.meta.outputs.tags }} \
            ${{ vars.DOCKER_REGISTRY }}/cocobay-app-frontend:latest
