name: Checks

on:
  pull_request:
    branches: [develop, main]
    paths:
      - Dockerfile*
      - .dockerignore
      - package.json
      - tsconfig.json
      - yarn.lock
      - .yarnrc.yml
      - "packages/**"

concurrency:
  group: pr-check-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
