name: Production deployment

on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      env: production

  deployment:
    name: Deploy to production
    environment: production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build
    steps:
      - name: Checkout branch
        id: git-checkout
        uses: actions/checkout@v4.2.1
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}

      #More steps needed later

  prod-branch-protection:
    name: Stop production release
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Unable to deploy
        run: "echo Only the main branch is allowed to be pushed to production"
