name: Test

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Install and cache
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.git-checkout.outputs.commit }}

    steps:
      - name: Checkout branch
        id: git-checkout
        uses: actions/checkout@main
        with:
          ref: ${{ github.event.inputs.branch || github.event.pull_request.head.ref || github.ref }}

      - name: Yarn Install
        uses: ./.github/workflows/actions/yarn-cache

  lint-check:
    name: Lint check
    runs-on: ubuntu-latest
    needs:
      - setup

    steps:
      - name: Checkout branch
        uses: actions/checkout@main
        with:
          ref: ${{ github.event.inputs.branch || github.event.pull_request.head.ref || github.ref }}

      - name: Yarn Install
        uses: ./.github/workflows/actions/yarn-cache

      - name: Lint checks
        run: |
          yarn lint:check

      - name: Cancel workflow if failed
        if: failure()
        uses: andymckay/cancel-action@0.4

  test-unit:
    name: Unit tests
    runs-on: ubuntu-latest
    needs:
      - setup

    steps:
      - name: Checkout branch
        uses: actions/checkout@main
        with:
          ref: ${{ github.event.inputs.branch || github.event.pull_request.head.ref || github.ref }}

      - name: Yarn Install
        uses: ./.github/workflows/actions/yarn-cache

      - name: Run all unit tests
        run: |
          yarn test:cov

      - name: Cancel workflow if failed
        if: failure()
        uses: andymckay/cancel-action@0.4

  test-e2e:
    name: End to end tests
    runs-on: ubuntu-latest
    needs:
      - setup

    steps:
      - name: Checkout branch
        uses: actions/checkout@main
        with:
          ref: ${{ github.event.inputs.branch || github.event.pull_request.head.ref || github.ref }}

      - name: Yarn Install
        uses: ./.github/workflows/actions/yarn-cache

      - name: Run all e2e tests
        run: |
          yarn test:e2e-cov

      - name: Cancel workflow if failed
        if: failure()
        uses: andymckay/cancel-action@0.4
